### ISSUE TITLE
Outdated custom-error-instance

### ISSUE THREAD

**Issue by ghaiklor-wix** [Gi60s/rolling-file#12]
Hi! I noticed that this package is using an outdated version of `custom-error-instance` that has redundant `console.log` call in its sources. Is there a possibility to update to the newer version? I could open a PR.

**Comment by ghaiklor-wix** [comment]
The way it affects our flow is that Jest treats the `console.log` specially :)

<img width="1904" alt="Screenshot 2020-07-09 at 20 07 23" src="https://user-images.githubusercontent.com/59873217/87072202-11b66a00-c224-11ea-8113-1ade581644cb.png">

**Comment by ghaiklor-wix** [comment]
@Gi60s ?

**Comment by Gi60s** [comment]
Sorry for the slow response. I've been out of town without cell reception. I'll take a look at this, probably tomorrow. I've got a lot to catch up on today. :)

**Comment by Gi60s** [comment]
A few meetings were cancelled this morning so I had a chance to update this. Get `rolling-file@1.1.0` to fix this issue. Thanks for the issue.

**Comment by ghaiklor-wix** [comment]
Thanks a lot! Really appreciate it :)
