### ISSUE TITLE
Creates new iterations of files on the same day.

### ISSUE THREAD

**Issue by alimovz** [Gi60s/rolling-file#13]
If my interval is set to '1 day', can I make the logger stick to the same file when I reinitialize it? Here is my code:

```
const postData = async (order_id) => {
    const logger = rollingFile('./logs/liveposts', { fileName: `order-${order_id}`, fileExtension: 'log', interval: '1 day' });
    for(let i = 0; i < 10; i++){
        await axios.post('http://example.net/'+order_id, {data: {w: 122}})
            .then(response => {
                logger.write(`${i}. http://example.net/orders/${order_id}`);
                logger.write(response.data)
            })
    }
}


```
postData is called from a cron every 10 minutes. The problem is that Rolling file will create a new iteration each time postData runs despite the fact that it's still the same day. The result is this:

- order-aaa.2020-10-26-000000.0.log
- order-aaa.2020-10-26-000000.1.log
- order-aaa.2020-10-26-000000.2.log

With a new file being created every 10 minutes. Can it detect that there is already a file for 2020-10-26 and continue to append to it until rolling it to 2020-10-27 the next day?

**Comment by Gi60s** [comment]
Any time you initialize a new `rollingFile` instance it's going to dump it into a new file. As long as your process keeps running you could try this pattern:

```js
const map = {}

const postData = async (order_id) => {
    if (!map[order_id]) map[order_id] = rollingFile('./logs/liveposts', { fileName: `order-${order_id}`, fileExtension: 'log', interval: '1 day' });
    const logger = map[order_id];
    for(let i = 0; i < 10; i++){
        await axios.post('http://example.net/'+order_id, {data: {w: 122}})
            .then(response => {
                logger.write(`${i}. http://example.net/orders/${order_id}`);
                logger.write(response.data)
            })
    }
}
```

**Comment by alimovz** [comment]
Thank you, sir.
