### ISSUE TITLE
write fails without callback given some error occurs within rolling-file.js#createNewStream()

### ISSUE THREAD

**Issue by viliusl** [Gi60s/rolling-file#3]
See #2 - this bug resulted in https://nodejs.org/api/process.html#process_event_unhandledrejection instead of callback with error (which I would have expected).

I tried to figure out some sane way to write a failing test and a fix for it, but did not yet found one. A fix could be just doing smth like https://lodash.com/docs#once and then making sure rolling-file.js#createNewStream() has a catch(e => callback(e)). This is a simple and not so great fix - other way around would be to promisify it all and call a callback in the end.

I did not wanted to get all crazy on code myself without first getting your feedback on direction this should take:
 - I will do a quick fix (.catch on promises);
 - I will promisify it all and have a catch at the end;
 - you will handle it:)

Cheers,
Vilius

**Comment by Gi60s** [comment]
I'll look into this and get back to you. Thanks.

**Comment by Gi60s** [comment]
I believe this has been fixed now. I've pushed to the repository and updated the npm repository. The callback will get the error now instead of there being an unhandled rejection error.

**Comment by viliusl** [comment]
Thanks alot!

**Comment by Gi60s** [comment]
Thanks for reporting the issue.
