### ISSUE TITLE
Any way to have the file go into a date directory?

### ISSUE THREAD

**Issue by jsbeltz** [Gi60s/rolling-file#4]

**Comment by Gi60s** [comment]
I'm not sure what you mean by a date directory. Can I get clarification?

**Comment by jsbeltz** [comment]
so say a log/yyyy-mm-dd/fileName.idx.fileExt

**Comment by Gi60s** [comment]
There is not a way to do that at the moment. The reason is that if you are writing to a rolling file and then your close the stream and re-open one with the same configuration then it identifies it's previous files and picks up where it left off. It may be possible to add this feature.
