### ISSUE TITLE
File Compression

### ISSUE THREAD

**Issue by johnmac-ph** [Gi60s/rolling-file#8]
Hi,
    Any chance to add file compression option for rolled-over files?

**Comment by Gi60s** [comment]
Sorry for the slow response. I think it's a possibility but there are some things to consider.

1. Should it compress each write individually? That wouldn't lead to very good compression.
2. Should it compress after finishing a file? If so then when is a file finished? Currently a file may be reopened for writing to if it has not yet reached the limits (time and size) it was designed for. In that case it might have to decompress a file before further writing.

What are your thoughts?
